# $FreeBSD$

PORTNAME=	chc
PORTVERSION=	0.2
CATEGORIES=	science
MASTER_SITES=	http://www.pozsarzs.hu/sources/

MAINTAINER=	pozsarzs@gmail.com
COMMENT=	Choking coil sizer

GNU_CONFIGURE=	yes

.include <bsd.port.mk>

CONFIGURE_ARGS+=stagedir=$(STAGEDIR)/$(PREFIX)

