.TH "chc" "7" "0.2" "Pozsar Zsolt" "Choking coil sizing application"
.SH "NAME"
.LP 
CHC \- Choking coil sizing application
.SH "SYNTAX"
.LP
chc [-h | --help | -v | --version]
.br 
.SH OPTIONS
.TP
.B \-h \-\-help
Write useable parameters to console.
.TP
.B \-v \-\-version
Write version number and build information to console.
.br 
.SH "DESCRIPTION"
.LP 
This is an sizing application for calculate EI core choking coils.
.br
.SH "ENVIRONMENTAL VARIABLE"
.LP 
\fBLANG\fP
.br
You can set language of labels with these variables.
If it is a non-supported language, text will be English.
Format: en, en_US.
.br
Available language are English and Hungarian.
.SH "AUTHOR"
.LP 
Pozsar Zsolt
.br
Web:    http://www.pozsarzs.hu/en
.br
E-mail: pozsarzs@gmail.com
