.TH "chc" "7" "0.2" "Pozsár Zsolt" "Fojtótekercs méretező alkalmazás"
.SH "NÉV"
.LP 
CHC \- Fojtótekercs méretező alkalmazás
.SH "ÁTTEKINTÉS"
.LP
chc [-h | --help | -v | --version]
.br
.SH OPCIÓK
.TP
.B \-h \-\-help
Kiírja a használható paramétereket a konzolra.
.TP
.B \-v \-\-version
Kiírja a verziószámot és a fordítási információt a konzolra.
.br
.SH "LEÍRÁS"
Ez egy fojtótekercs méretező alkalmazás EI vasmagos tekercsek számításához.
.LP 
.SH "KÖRNYEZETI VÁLTOZÓK"
.LP 
\fBLANG\fP
.br
Evvel a környezeti változóval állíthatjuk be a program nyelvezetét. Ha
ez egy nem támogatott nyelv, akkor a feliratok angol nyelvűek lesznek.
Alak: hu, hu_HU.
.br
Jelenleg elérhető nyelvek: angol, magyar.
.SH "SZERZŐ"
.LP 
Pozsár Zsolt
.br
Web:    http://www.pozsarzs.hu
.br
E-mail: pozsarzs@gmail.com
